/* tslint:disable */
/* eslint-disable */
/*
PGW Payment API 4.3

Rest API for PGW payment purpose - LATEST

The version of the OpenAPI document: 4.3


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/

import globalAxios, { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, isBrowser } from '../common';
import { fromBuffer } from "file-type/browser"
const FormData = require("form-data")
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
// @ts-ignore
import { BrowserDetails } from '../models';
// @ts-ignore
import { PaymentBaseRequest } from '../models';
// @ts-ignore
import { PaymentCardTokenResponseV43 } from '../models';
import { paginate } from "../pagination/paginate";
import type * as buffer from "buffer"
import { requestBeforeHook } from '../requestBeforeHook';
/**
 * CardTokenInfoApi - axios parameter creator
 * @export
 */
export const CardTokenInfoApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary 
         * @param {PaymentBaseRequest} [paymentBaseRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getCardTokenInfo: async (paymentBaseRequest?: PaymentBaseRequest, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/payment/4.3/cardtokeninfo`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions: AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = configuration && !isBrowser() ? { "User-Agent": configuration.userAgent } : {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';


            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            requestBeforeHook({
                requestBody: paymentBaseRequest,
                queryParameters: localVarQueryParameter,
                requestConfig: localVarRequestOptions,
                path: localVarPath,
                configuration,
                pathTemplate: '/payment/4.3/cardtokeninfo',
                httpMethod: 'POST'
            });
            localVarRequestOptions.data = serializeDataIfNeeded(paymentBaseRequest, localVarRequestOptions, configuration)

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * CardTokenInfoApi - functional programming interface
 * @export
 */
export const CardTokenInfoApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = CardTokenInfoApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary 
         * @param {CardTokenInfoApiGetCardTokenInfoRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getCardTokenInfo(requestParameters: CardTokenInfoApiGetCardTokenInfoRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<PaymentCardTokenResponseV43>> {
            const paymentBaseRequest: PaymentBaseRequest = {
                paymentToken: requestParameters.paymentToken,
                locale: requestParameters.locale,
                clientID: requestParameters.clientID,
                browserDetails: requestParameters.browserDetails
            };
            const localVarAxiosArgs = await localVarAxiosParamCreator.getCardTokenInfo(paymentBaseRequest, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * CardTokenInfoApi - factory interface
 * @export
 */
export const CardTokenInfoApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = CardTokenInfoApiFp(configuration)
    return {
        /**
         * 
         * @summary 
         * @param {CardTokenInfoApiGetCardTokenInfoRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getCardTokenInfo(requestParameters: CardTokenInfoApiGetCardTokenInfoRequest, options?: AxiosRequestConfig): AxiosPromise<PaymentCardTokenResponseV43> {
            return localVarFp.getCardTokenInfo(requestParameters, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for getCardTokenInfo operation in CardTokenInfoApi.
 * @export
 * @interface CardTokenInfoApiGetCardTokenInfoRequest
 */
export type CardTokenInfoApiGetCardTokenInfoRequest = {
    
} & PaymentBaseRequest

/**
 * CardTokenInfoApiGenerated - object-oriented interface
 * @export
 * @class CardTokenInfoApiGenerated
 * @extends {BaseAPI}
 */
export class CardTokenInfoApiGenerated extends BaseAPI {
    /**
     * 
     * @summary 
     * @param {CardTokenInfoApiGetCardTokenInfoRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CardTokenInfoApiGenerated
     */
    public getCardTokenInfo(requestParameters: CardTokenInfoApiGetCardTokenInfoRequest, options?: AxiosRequestConfig) {
        return CardTokenInfoApiFp(this.configuration).getCardTokenInfo(requestParameters, options).then((request) => request(this.axios, this.basePath));
    }
}
