/* tslint:disable */
/* eslint-disable */
/*
PGW Payment API 4.3

Rest API for PGW payment purpose - LATEST

The version of the OpenAPI document: 4.3


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/

import globalAxios, { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, isBrowser } from '../common';
import { fromBuffer } from "file-type/browser"
const FormData = require("form-data")
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
// @ts-ignore
import { BrowserDetails } from '../models';
// @ts-ignore
import { CardInstallmentPlanInfoRequest } from '../models';
// @ts-ignore
import { PaymentOptionDetailsResponse } from '../models';
import { paginate } from "../pagination/paginate";
import type * as buffer from "buffer"
import { requestBeforeHook } from '../requestBeforeHook';
/**
 * CardInstallmentPlanInfoApi - axios parameter creator
 * @export
 */
export const CardInstallmentPlanInfoApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {CardInstallmentPlanInfoRequest} [cardInstallmentPlanInfoRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        create: async (cardInstallmentPlanInfoRequest?: CardInstallmentPlanInfoRequest, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/payment/4.3/cardinstallmentplaninfo`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions: AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = configuration && !isBrowser() ? { "User-Agent": configuration.userAgent } : {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';


            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            requestBeforeHook({
                requestBody: cardInstallmentPlanInfoRequest,
                queryParameters: localVarQueryParameter,
                requestConfig: localVarRequestOptions,
                path: localVarPath,
                configuration,
                pathTemplate: '/payment/4.3/cardinstallmentplaninfo',
                httpMethod: 'POST'
            });
            localVarRequestOptions.data = serializeDataIfNeeded(cardInstallmentPlanInfoRequest, localVarRequestOptions, configuration)

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * CardInstallmentPlanInfoApi - functional programming interface
 * @export
 */
export const CardInstallmentPlanInfoApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = CardInstallmentPlanInfoApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {CardInstallmentPlanInfoApiCreateRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async create(requestParameters: CardInstallmentPlanInfoApiCreateRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<PaymentOptionDetailsResponse>> {
            const cardInstallmentPlanInfoRequest: CardInstallmentPlanInfoRequest = {
                cardNo: requestParameters.cardNo,
                bankCode: requestParameters.bankCode,
                paymentToken: requestParameters.paymentToken,
                locale: requestParameters.locale,
                clientID: requestParameters.clientID,
                browserDetails: requestParameters.browserDetails
            };
            const localVarAxiosArgs = await localVarAxiosParamCreator.create(cardInstallmentPlanInfoRequest, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * CardInstallmentPlanInfoApi - factory interface
 * @export
 */
export const CardInstallmentPlanInfoApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = CardInstallmentPlanInfoApiFp(configuration)
    return {
        /**
         * 
         * @param {CardInstallmentPlanInfoApiCreateRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        create(requestParameters: CardInstallmentPlanInfoApiCreateRequest, options?: AxiosRequestConfig): AxiosPromise<PaymentOptionDetailsResponse> {
            return localVarFp.create(requestParameters, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for create operation in CardInstallmentPlanInfoApi.
 * @export
 * @interface CardInstallmentPlanInfoApiCreateRequest
 */
export type CardInstallmentPlanInfoApiCreateRequest = {
    
} & CardInstallmentPlanInfoRequest

/**
 * CardInstallmentPlanInfoApiGenerated - object-oriented interface
 * @export
 * @class CardInstallmentPlanInfoApiGenerated
 * @extends {BaseAPI}
 */
export class CardInstallmentPlanInfoApiGenerated extends BaseAPI {
    /**
     * 
     * @param {CardInstallmentPlanInfoApiCreateRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CardInstallmentPlanInfoApiGenerated
     */
    public create(requestParameters: CardInstallmentPlanInfoApiCreateRequest, options?: AxiosRequestConfig) {
        return CardInstallmentPlanInfoApiFp(this.configuration).create(requestParameters, options).then((request) => request(this.axios, this.basePath));
    }
}
