/* tslint:disable */
/* eslint-disable */
/*
PGW Payment API 4.3

Rest API for PGW payment purpose - LATEST

The version of the OpenAPI document: 4.3


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/

import globalAxios, { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, isBrowser } from '../common';
import { fromBuffer } from "file-type/browser"
const FormData = require("form-data")
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
// @ts-ignore
import { BrowserDetails } from '../models';
// @ts-ignore
import { PaymentLoyaltyPointInfoRequest } from '../models';
// @ts-ignore
import { PaymentLoyaltyPointInfoResponse } from '../models';
import { paginate } from "../pagination/paginate";
import type * as buffer from "buffer"
import { requestBeforeHook } from '../requestBeforeHook';
/**
 * LoyaltyPointInfoApi - axios parameter creator
 * @export
 */
export const LoyaltyPointInfoApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary 
         * @param {PaymentLoyaltyPointInfoRequest} [paymentLoyaltyPointInfoRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        postLoyaltyPointInfo: async (paymentLoyaltyPointInfoRequest?: PaymentLoyaltyPointInfoRequest, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/payment/4.3/loyaltypointinfo`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions: AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = configuration && !isBrowser() ? { "User-Agent": configuration.userAgent } : {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';


            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            requestBeforeHook({
                requestBody: paymentLoyaltyPointInfoRequest,
                queryParameters: localVarQueryParameter,
                requestConfig: localVarRequestOptions,
                path: localVarPath,
                configuration,
                pathTemplate: '/payment/4.3/loyaltypointinfo',
                httpMethod: 'POST'
            });
            localVarRequestOptions.data = serializeDataIfNeeded(paymentLoyaltyPointInfoRequest, localVarRequestOptions, configuration)

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * LoyaltyPointInfoApi - functional programming interface
 * @export
 */
export const LoyaltyPointInfoApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = LoyaltyPointInfoApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary 
         * @param {LoyaltyPointInfoApiPostLoyaltyPointInfoRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async postLoyaltyPointInfo(requestParameters: LoyaltyPointInfoApiPostLoyaltyPointInfoRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<PaymentLoyaltyPointInfoResponse>> {
            const paymentLoyaltyPointInfoRequest: PaymentLoyaltyPointInfoRequest = {
                providerID: requestParameters.providerID,
                profileID: requestParameters.profileID,
                referenceID: requestParameters.referenceID,
                cardNo: requestParameters.cardNo,
                expiryMonth: requestParameters.expiryMonth,
                expiryYear: requestParameters.expiryYear,
                paymentToken: requestParameters.paymentToken,
                locale: requestParameters.locale,
                clientID: requestParameters.clientID,
                browserDetails: requestParameters.browserDetails
            };
            const localVarAxiosArgs = await localVarAxiosParamCreator.postLoyaltyPointInfo(paymentLoyaltyPointInfoRequest, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * LoyaltyPointInfoApi - factory interface
 * @export
 */
export const LoyaltyPointInfoApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = LoyaltyPointInfoApiFp(configuration)
    return {
        /**
         * 
         * @summary 
         * @param {LoyaltyPointInfoApiPostLoyaltyPointInfoRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        postLoyaltyPointInfo(requestParameters: LoyaltyPointInfoApiPostLoyaltyPointInfoRequest, options?: AxiosRequestConfig): AxiosPromise<PaymentLoyaltyPointInfoResponse> {
            return localVarFp.postLoyaltyPointInfo(requestParameters, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for postLoyaltyPointInfo operation in LoyaltyPointInfoApi.
 * @export
 * @interface LoyaltyPointInfoApiPostLoyaltyPointInfoRequest
 */
export type LoyaltyPointInfoApiPostLoyaltyPointInfoRequest = {
    
} & PaymentLoyaltyPointInfoRequest

/**
 * LoyaltyPointInfoApiGenerated - object-oriented interface
 * @export
 * @class LoyaltyPointInfoApiGenerated
 * @extends {BaseAPI}
 */
export class LoyaltyPointInfoApiGenerated extends BaseAPI {
    /**
     * 
     * @summary 
     * @param {LoyaltyPointInfoApiPostLoyaltyPointInfoRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof LoyaltyPointInfoApiGenerated
     */
    public postLoyaltyPointInfo(requestParameters: LoyaltyPointInfoApiPostLoyaltyPointInfoRequest, options?: AxiosRequestConfig) {
        return LoyaltyPointInfoApiFp(this.configuration).postLoyaltyPointInfo(requestParameters, options).then((request) => request(this.axios, this.basePath));
    }
}
