/* tslint:disable */
/* eslint-disable */
/*
PGW Payment API 4.3

Rest API for PGW payment purpose - LATEST

The version of the OpenAPI document: 4.3


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/

import globalAxios, { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, isBrowser } from '../common';
import { fromBuffer } from "file-type/browser"
const FormData = require("form-data")
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
// @ts-ignore
import { BrowserDetails } from '../models';
// @ts-ignore
import { PaymentBaseRequest } from '../models';
// @ts-ignore
import { PaymentOptionResponse } from '../models';
import { paginate } from "../pagination/paginate";
import type * as buffer from "buffer"
import { requestBeforeHook } from '../requestBeforeHook';
/**
 * PaymentOptionApi - axios parameter creator
 * @export
 */
export const PaymentOptionApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary 
         * @param {PaymentBaseRequest} [paymentBaseRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createPaymentOption: async (paymentBaseRequest?: PaymentBaseRequest, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/payment/4.3/paymentoption`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions: AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = configuration && !isBrowser() ? { "User-Agent": configuration.userAgent } : {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';


            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            requestBeforeHook({
                requestBody: paymentBaseRequest,
                queryParameters: localVarQueryParameter,
                requestConfig: localVarRequestOptions,
                path: localVarPath,
                configuration,
                pathTemplate: '/payment/4.3/paymentoption',
                httpMethod: 'POST'
            });
            localVarRequestOptions.data = serializeDataIfNeeded(paymentBaseRequest, localVarRequestOptions, configuration)

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * PaymentOptionApi - functional programming interface
 * @export
 */
export const PaymentOptionApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = PaymentOptionApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary 
         * @param {PaymentOptionApiCreatePaymentOptionRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createPaymentOption(requestParameters: PaymentOptionApiCreatePaymentOptionRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<PaymentOptionResponse>> {
            const paymentBaseRequest: PaymentBaseRequest = {
                paymentToken: requestParameters.paymentToken,
                locale: requestParameters.locale,
                clientID: requestParameters.clientID,
                browserDetails: requestParameters.browserDetails
            };
            const localVarAxiosArgs = await localVarAxiosParamCreator.createPaymentOption(paymentBaseRequest, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * PaymentOptionApi - factory interface
 * @export
 */
export const PaymentOptionApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = PaymentOptionApiFp(configuration)
    return {
        /**
         * 
         * @summary 
         * @param {PaymentOptionApiCreatePaymentOptionRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createPaymentOption(requestParameters: PaymentOptionApiCreatePaymentOptionRequest, options?: AxiosRequestConfig): AxiosPromise<PaymentOptionResponse> {
            return localVarFp.createPaymentOption(requestParameters, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for createPaymentOption operation in PaymentOptionApi.
 * @export
 * @interface PaymentOptionApiCreatePaymentOptionRequest
 */
export type PaymentOptionApiCreatePaymentOptionRequest = {
    
} & PaymentBaseRequest

/**
 * PaymentOptionApiGenerated - object-oriented interface
 * @export
 * @class PaymentOptionApiGenerated
 * @extends {BaseAPI}
 */
export class PaymentOptionApiGenerated extends BaseAPI {
    /**
     * 
     * @summary 
     * @param {PaymentOptionApiCreatePaymentOptionRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PaymentOptionApiGenerated
     */
    public createPaymentOption(requestParameters: PaymentOptionApiCreatePaymentOptionRequest, options?: AxiosRequestConfig) {
        return PaymentOptionApiFp(this.configuration).createPaymentOption(requestParameters, options).then((request) => request(this.axios, this.basePath));
    }
}
