/* tslint:disable */
/* eslint-disable */
/*
PGW Payment API 4.3

Rest API for PGW payment purpose - LATEST

The version of the OpenAPI document: 4.3


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/

import globalAxios, { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, isBrowser } from '../common';
import { fromBuffer } from "file-type/browser"
const FormData = require("form-data")
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
// @ts-ignore
import { BrowserDetails } from '../models';
// @ts-ignore
import { TransactionStatusRequest } from '../models';
// @ts-ignore
import { TransactionStatusResponse } from '../models';
import { paginate } from "../pagination/paginate";
import type * as buffer from "buffer"
import { requestBeforeHook } from '../requestBeforeHook';
/**
 * TransactionStatusApi - axios parameter creator
 * @export
 */
export const TransactionStatusApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary 
         * @param {TransactionStatusRequest} [transactionStatusRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateTransactionStatus: async (transactionStatusRequest?: TransactionStatusRequest, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/payment/4.3/transactionstatus`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions: AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = configuration && !isBrowser() ? { "User-Agent": configuration.userAgent } : {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';


            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            requestBeforeHook({
                requestBody: transactionStatusRequest,
                queryParameters: localVarQueryParameter,
                requestConfig: localVarRequestOptions,
                path: localVarPath,
                configuration,
                pathTemplate: '/payment/4.3/transactionstatus',
                httpMethod: 'POST'
            });
            localVarRequestOptions.data = serializeDataIfNeeded(transactionStatusRequest, localVarRequestOptions, configuration)

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * TransactionStatusApi - functional programming interface
 * @export
 */
export const TransactionStatusApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = TransactionStatusApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary 
         * @param {TransactionStatusApiUpdateTransactionStatusRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateTransactionStatus(requestParameters: TransactionStatusApiUpdateTransactionStatusRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<TransactionStatusResponse>> {
            const transactionStatusRequest: TransactionStatusRequest = {
                additionalInfo: requestParameters.additionalInfo,
                paymentToken: requestParameters.paymentToken,
                locale: requestParameters.locale,
                clientID: requestParameters.clientID,
                browserDetails: requestParameters.browserDetails
            };
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateTransactionStatus(transactionStatusRequest, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * TransactionStatusApi - factory interface
 * @export
 */
export const TransactionStatusApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = TransactionStatusApiFp(configuration)
    return {
        /**
         * 
         * @summary 
         * @param {TransactionStatusApiUpdateTransactionStatusRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateTransactionStatus(requestParameters: TransactionStatusApiUpdateTransactionStatusRequest, options?: AxiosRequestConfig): AxiosPromise<TransactionStatusResponse> {
            return localVarFp.updateTransactionStatus(requestParameters, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for updateTransactionStatus operation in TransactionStatusApi.
 * @export
 * @interface TransactionStatusApiUpdateTransactionStatusRequest
 */
export type TransactionStatusApiUpdateTransactionStatusRequest = {
    
} & TransactionStatusRequest

/**
 * TransactionStatusApiGenerated - object-oriented interface
 * @export
 * @class TransactionStatusApiGenerated
 * @extends {BaseAPI}
 */
export class TransactionStatusApiGenerated extends BaseAPI {
    /**
     * 
     * @summary 
     * @param {TransactionStatusApiUpdateTransactionStatusRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TransactionStatusApiGenerated
     */
    public updateTransactionStatus(requestParameters: TransactionStatusApiUpdateTransactionStatusRequest, options?: AxiosRequestConfig) {
        return TransactionStatusApiFp(this.configuration).updateTransactionStatus(requestParameters, options).then((request) => request(this.axios, this.basePath));
    }
}
