/* tslint:disable */
/* eslint-disable */
/*
PGW Payment API 4.3

Rest API for PGW payment purpose - LATEST

The version of the OpenAPI document: 4.3


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/

import globalAxios, { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, isBrowser } from '../common';
import { fromBuffer } from "file-type/browser"
const FormData = require("form-data")
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
// @ts-ignore
import { BrowserDetails } from '../models';
// @ts-ignore
import { PaymentBaseRequest } from '../models';
// @ts-ignore
import { PaymentUserPreferenceResponse } from '../models';
import { paginate } from "../pagination/paginate";
import type * as buffer from "buffer"
import { requestBeforeHook } from '../requestBeforeHook';
/**
 * UserPreferenceApi - axios parameter creator
 * @export
 */
export const UserPreferenceApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary 
         * @param {PaymentBaseRequest} [paymentBaseRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        saveUserPreference: async (paymentBaseRequest?: PaymentBaseRequest, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/payment/4.3/userpreference`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions: AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = configuration && !isBrowser() ? { "User-Agent": configuration.userAgent } : {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';


            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            requestBeforeHook({
                requestBody: paymentBaseRequest,
                queryParameters: localVarQueryParameter,
                requestConfig: localVarRequestOptions,
                path: localVarPath,
                configuration,
                pathTemplate: '/payment/4.3/userpreference',
                httpMethod: 'POST'
            });
            localVarRequestOptions.data = serializeDataIfNeeded(paymentBaseRequest, localVarRequestOptions, configuration)

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * UserPreferenceApi - functional programming interface
 * @export
 */
export const UserPreferenceApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = UserPreferenceApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary 
         * @param {UserPreferenceApiSaveUserPreferenceRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async saveUserPreference(requestParameters: UserPreferenceApiSaveUserPreferenceRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<PaymentUserPreferenceResponse>> {
            const paymentBaseRequest: PaymentBaseRequest = {
                paymentToken: requestParameters.paymentToken,
                locale: requestParameters.locale,
                clientID: requestParameters.clientID,
                browserDetails: requestParameters.browserDetails
            };
            const localVarAxiosArgs = await localVarAxiosParamCreator.saveUserPreference(paymentBaseRequest, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * UserPreferenceApi - factory interface
 * @export
 */
export const UserPreferenceApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = UserPreferenceApiFp(configuration)
    return {
        /**
         * 
         * @summary 
         * @param {UserPreferenceApiSaveUserPreferenceRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        saveUserPreference(requestParameters: UserPreferenceApiSaveUserPreferenceRequest, options?: AxiosRequestConfig): AxiosPromise<PaymentUserPreferenceResponse> {
            return localVarFp.saveUserPreference(requestParameters, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for saveUserPreference operation in UserPreferenceApi.
 * @export
 * @interface UserPreferenceApiSaveUserPreferenceRequest
 */
export type UserPreferenceApiSaveUserPreferenceRequest = {
    
} & PaymentBaseRequest

/**
 * UserPreferenceApiGenerated - object-oriented interface
 * @export
 * @class UserPreferenceApiGenerated
 * @extends {BaseAPI}
 */
export class UserPreferenceApiGenerated extends BaseAPI {
    /**
     * 
     * @summary 
     * @param {UserPreferenceApiSaveUserPreferenceRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UserPreferenceApiGenerated
     */
    public saveUserPreference(requestParameters: UserPreferenceApiSaveUserPreferenceRequest, options?: AxiosRequestConfig) {
        return UserPreferenceApiFp(this.configuration).saveUserPreference(requestParameters, options).then((request) => request(this.axios, this.basePath));
    }
}
