/*
PGW Payment API 4.3

Rest API for PGW payment purpose - LATEST

The version of the OpenAPI document: 4.3


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface Address
 */
export interface Address {
    /**
     * 
     * @type {string}
     * @memberof Address
     */
    'address1'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Address
     */
    'address2'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Address
     */
    'address3'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Address
     */
    'postalCode'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Address
     */
    'city'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Address
     */
    'state'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Address
     */
    'countryCode'?: string | null;
}

