/*
PGW Payment API 4.3

Rest API for PGW payment purpose - LATEST

The version of the OpenAPI document: 4.3


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface BrowserDetails
 */
export interface BrowserDetails {
    /**
     * 
     * @type {string}
     * @memberof BrowserDetails
     */
    'version'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof BrowserDetails
     */
    'deviceType'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof BrowserDetails
     */
    'name'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof BrowserDetails
     */
    'os'?: string | null;
}

