/*
PGW Payment API 4.3

Rest API for PGW payment purpose - LATEST

The version of the OpenAPI document: 4.3


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface CreditCardTokenV43
 */
export interface CreditCardTokenV43 {
    /**
     * 
     * @type {string}
     * @memberof CreditCardTokenV43
     */
    'token'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreditCardTokenV43
     */
    'accountNo'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreditCardTokenV43
     */
    'name'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreditCardTokenV43
     */
    'email'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreditCardTokenV43
     */
    'expiry'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreditCardTokenV43
     */
    'channelCode'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreditCardTokenV43
     */
    'subChannelCode'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreditCardTokenV43
     */
    'cardBrand'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreditCardTokenV43
     */
    'status'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreditCardTokenV43
     */
    'iconUrl'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreditCardTokenV43
     */
    'logoUrl'?: string | null;
}

