/*
PGW Payment API 4.3

Rest API for PGW payment purpose - LATEST

The version of the OpenAPI document: 4.3


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface CurrencyFxRate
 */
export interface CurrencyFxRate {
    /**
     * 
     * @type {string}
     * @memberof CurrencyFxRate
     */
    'name'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CurrencyFxRate
     */
    'iconUrl'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CurrencyFxRate
     */
    'amount'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof CurrencyFxRate
     */
    'sequenceNo'?: number;
    /**
     * 
     * @type {string}
     * @memberof CurrencyFxRate
     */
    'id'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof CurrencyFxRate
     */
    'fx'?: number;
    /**
     * 
     * @type {string}
     * @memberof CurrencyFxRate
     */
    'currencyCode'?: string | null;
}

