/*
PGW Payment API 4.3

Rest API for PGW payment purpose - LATEST

The version of the OpenAPI document: 4.3


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface CurrencyAPMMCCFxRate
 */
export interface CurrencyAPMMCCFxRate {
    /**
     * 
     * @type {number}
     * @memberof CurrencyAPMMCCFxRate
     */
    'expire'?: number;
    /**
     * 
     * @type {number}
     * @memberof CurrencyAPMMCCFxRate
     */
    'sequenceNo'?: number;
    /**
     * 
     * @type {string}
     * @memberof CurrencyAPMMCCFxRate
     */
    'id'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof CurrencyAPMMCCFxRate
     */
    'fx'?: number;
    /**
     * 
     * @type {string}
     * @memberof CurrencyAPMMCCFxRate
     */
    'currencyCode'?: string | null;
}

