/*
PGW Payment API 4.3

Rest API for PGW payment purpose - LATEST

The version of the OpenAPI document: 4.3


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Address } from './address';

/**
 * 
 * @export
 * @interface CustomerAddress
 */
export interface CustomerAddress {
    /**
     * 
     * @type {Address}
     * @memberof CustomerAddress
     */
    'billing'?: Address;
    /**
     * 
     * @type {Address}
     * @memberof CustomerAddress
     */
    'shipping'?: Address;
}

