/*
PGW Payment API 4.3

Rest API for PGW payment purpose - LATEST

The version of the OpenAPI document: 4.3


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface IppPlan
 */
export interface IppPlan {
    /**
     * 
     * @type {number}
     * @memberof IppPlan
     */
    'sequenceNo'?: number;
    /**
     * 
     * @type {number}
     * @memberof IppPlan
     */
    'period'?: number;
    /**
     * 
     * @type {string}
     * @memberof IppPlan
     */
    'interestType'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof IppPlan
     */
    'interestRate'?: number;
    /**
     * 
     * @type {number}
     * @memberof IppPlan
     */
    'monthlyAmount'?: number;
    /**
     * 
     * @type {number}
     * @memberof IppPlan
     */
    'monthlyInterest'?: number;
    /**
     * 
     * @type {string}
     * @memberof IppPlan
     */
    'currencyCode'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof IppPlan
     */
    'label'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof IppPlan
     */
    'terms'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof IppPlan
     */
    'payLaterPeriod'?: number | null;
}

