/*
PGW Payment API 4.3

Rest API for PGW payment purpose - LATEST

The version of the OpenAPI document: 4.3


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface Locale
 */
export interface Locale {
    /**
     * 
     * @type {string}
     * @memberof Locale
     */
    'code'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Locale
     */
    'name'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Locale
     */
    'iconUrl'?: string | null;
}

