/*
PGW Payment API 4.3

Rest API for PGW payment purpose - LATEST

The version of the OpenAPI document: 4.3


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { LoyaltyRewards } from './loyalty-rewards';

/**
 * 
 * @export
 * @interface LoyaltyDetails
 */
export interface LoyaltyDetails {
    /**
     * 
     * @type {string}
     * @memberof LoyaltyDetails
     */
    'providerID'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof LoyaltyDetails
     */
    'accountNo'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof LoyaltyDetails
     */
    'accountAuthData'?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof LoyaltyDetails
     */
    'queryReferenceSpecified'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof LoyaltyDetails
     */
    'externalMerchantId'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof LoyaltyDetails
     */
    'redeemAmount'?: number;
    /**
     * 
     * @type {Array<LoyaltyRewards>}
     * @memberof LoyaltyDetails
     */
    'rewards'?: Array<LoyaltyRewards> | null;
}

