/*
PGW Payment API 4.3

Rest API for PGW payment purpose - LATEST

The version of the OpenAPI document: 4.3


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { MerchantConfigurationNotification } from './merchant-configuration-notification';
import { MerchantConfigurationPayment } from './merchant-configuration-payment';

/**
 * 
 * @export
 * @interface MerchantConfiguration
 */
export interface MerchantConfiguration {
    /**
     * 
     * @type {MerchantConfigurationPayment}
     * @memberof MerchantConfiguration
     */
    'payment'?: MerchantConfigurationPayment;
    /**
     * 
     * @type {MerchantConfigurationNotification}
     * @memberof MerchantConfiguration
     */
    'notification'?: MerchantConfigurationNotification;
}

