/*
PGW Payment API 4.3

Rest API for PGW payment purpose - LATEST

The version of the OpenAPI document: 4.3


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface MerchantDetails
 */
export interface MerchantDetails {
    /**
     * 
     * @type {string}
     * @memberof MerchantDetails
     */
    'id'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof MerchantDetails
     */
    'name'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof MerchantDetails
     */
    'address'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof MerchantDetails
     */
    'email'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof MerchantDetails
     */
    'logoUrl'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof MerchantDetails
     */
    'bannerUrl'?: string | null;
}

