/*
PGW Payment API 4.3

Rest API for PGW payment purpose - LATEST

The version of the OpenAPI document: 4.3


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface MerchantConfigurationNotification
 */
export interface MerchantConfigurationNotification {
    /**
     * 
     * @type {boolean}
     * @memberof MerchantConfigurationNotification
     */
    'facebook'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof MerchantConfigurationNotification
     */
    'whatsApp'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof MerchantConfigurationNotification
     */
    'line'?: boolean;
}

