/*
PGW Payment API 4.3

Rest API for PGW payment purpose - LATEST

The version of the OpenAPI document: 4.3


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { MerchantConfigurationPaymentFx } from './merchant-configuration-payment-fx';

/**
 * 
 * @export
 * @interface MerchantConfigurationPayment
 */
export interface MerchantConfigurationPayment {
    /**
     * 
     * @type {boolean}
     * @memberof MerchantConfigurationPayment
     */
    'tokenize'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof MerchantConfigurationPayment
     */
    'tokenizeOnly'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof MerchantConfigurationPayment
     */
    'cardTokenOnly'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof MerchantConfigurationPayment
     */
    'immediatePayment'?: boolean;
    /**
     * 
     * @type {MerchantConfigurationPaymentFx}
     * @memberof MerchantConfigurationPayment
     */
    'fx'?: MerchantConfigurationPaymentFx;
}

