/*
PGW Payment API 4.3

Rest API for PGW payment purpose - LATEST

The version of the OpenAPI document: 4.3


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface MerchantValidationApplePayResponse
 */
export interface MerchantValidationApplePayResponse {
    /**
     * 
     * @type {number}
     * @memberof MerchantValidationApplePayResponse
     */
    'epochTimestamp'?: number;
    /**
     * 
     * @type {number}
     * @memberof MerchantValidationApplePayResponse
     */
    'expiresAt'?: number;
    /**
     * 
     * @type {string}
     * @memberof MerchantValidationApplePayResponse
     */
    'merchantSessionIdentifier'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof MerchantValidationApplePayResponse
     */
    'nonce'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof MerchantValidationApplePayResponse
     */
    'merchantIdentifier'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof MerchantValidationApplePayResponse
     */
    'domainName'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof MerchantValidationApplePayResponse
     */
    'displayName'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof MerchantValidationApplePayResponse
     */
    'signature'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof MerchantValidationApplePayResponse
     */
    'operationalAnalyticsIdentifier'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof MerchantValidationApplePayResponse
     */
    'retries'?: number;
    /**
     * 
     * @type {string}
     * @memberof MerchantValidationApplePayResponse
     */
    'pspId'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof MerchantValidationApplePayResponse
     */
    'respCode'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof MerchantValidationApplePayResponse
     */
    'respDesc'?: string | null;
}

