/*
PGW Payment API 4.3

Rest API for PGW payment purpose - LATEST

The version of the OpenAPI document: 4.3


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { PaymentOptionDetailsInfo } from './payment-option-details-info';
import { PaymentOptionDetailsPaymentCode } from './payment-option-details-payment-code';

/**
 * 
 * @export
 * @interface PaymentOptionDetailsPayment
 */
export interface PaymentOptionDetailsPayment {
    /**
     * 
     * @type {PaymentOptionDetailsInfo}
     * @memberof PaymentOptionDetailsPayment
     */
    'info'?: PaymentOptionDetailsInfo;
    /**
     * 
     * @type {PaymentOptionDetailsPaymentCode}
     * @memberof PaymentOptionDetailsPayment
     */
    'code'?: PaymentOptionDetailsPaymentCode;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof PaymentOptionDetailsPayment
     */
    'input'?: { [key: string]: any; } | null;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof PaymentOptionDetailsPayment
     */
    'validation'?: { [key: string]: any; } | null;
}

