/*
PGW Payment API 4.3

Rest API for PGW payment purpose - LATEST

The version of the OpenAPI document: 4.3


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { LoyaltyDetails } from './loyalty-details';

/**
 * 
 * @export
 * @interface PaymentParamsDataRequestV43
 */
export interface PaymentParamsDataRequestV43 {
    /**
     * 
     * @type {boolean}
     * @memberof PaymentParamsDataRequestV43
     */
    'accountTokenization'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof PaymentParamsDataRequestV43
     */
    'customerToken'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaymentParamsDataRequestV43
     */
    'name'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaymentParamsDataRequestV43
     */
    'email'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaymentParamsDataRequestV43
     */
    'mobileNo'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaymentParamsDataRequestV43
     */
    'accountNo'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaymentParamsDataRequestV43
     */
    'securePayToken'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaymentParamsDataRequestV43
     */
    'cardBank'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaymentParamsDataRequestV43
     */
    'cardCountry'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof PaymentParamsDataRequestV43
     */
    'installmentPeriod'?: number;
    /**
     * 
     * @type {number}
     * @memberof PaymentParamsDataRequestV43
     */
    'payLaterPeriod'?: number | null;
    /**
     * 
     * @type {string}
     * @memberof PaymentParamsDataRequestV43
     */
    'interestType'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaymentParamsDataRequestV43
     */
    'securityCode'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaymentParamsDataRequestV43
     */
    'qrType'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaymentParamsDataRequestV43
     */
    'fxRateID'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaymentParamsDataRequestV43
     */
    'billingAddress1'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaymentParamsDataRequestV43
     */
    'billingAddress2'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaymentParamsDataRequestV43
     */
    'billingAddress3'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaymentParamsDataRequestV43
     */
    'billingCity'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaymentParamsDataRequestV43
     */
    'billingState'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaymentParamsDataRequestV43
     */
    'billingPostalCode'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaymentParamsDataRequestV43
     */
    'billingCountryCode'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaymentParamsDataRequestV43
     */
    'paymentExpiry'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaymentParamsDataRequestV43
     */
    'cardNo'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaymentParamsDataRequestV43
     */
    'expiryMonth'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaymentParamsDataRequestV43
     */
    'expiryYear'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaymentParamsDataRequestV43
     */
    'pin'?: string | null;
    /**
     * 
     * @type {Array<LoyaltyDetails>}
     * @memberof PaymentParamsDataRequestV43
     */
    'loyaltyPoints'?: Array<LoyaltyDetails> | null;
    /**
     * 
     * @type {string}
     * @memberof PaymentParamsDataRequestV43
     */
    'customerNote'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaymentParamsDataRequestV43
     */
    'userAgent'?: string | null;
}

