/*
PGW Payment API 4.3

Rest API for PGW payment purpose - LATEST

The version of the OpenAPI document: 4.3


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Locale } from './locale';

/**
 * 
 * @export
 * @interface PaymentInitialization
 */
export interface PaymentInitialization {
    /**
     * 
     * @type {Array<Locale>}
     * @memberof PaymentInitialization
     */
    'locale'?: Array<Locale> | null;
}

