/*
PGW Payment API 4.3

Rest API for PGW payment purpose - LATEST

The version of the OpenAPI document: 4.3


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { PaymentOptionDetailsPayment } from './payment-option-details-payment';

/**
 * 
 * @export
 * @interface PaymentOptionDetailsChannel
 */
export interface PaymentOptionDetailsChannel {
    /**
     * 
     * @type {number}
     * @memberof PaymentOptionDetailsChannel
     */
    'sequenceNo'?: number;
    /**
     * 
     * @type {string}
     * @memberof PaymentOptionDetailsChannel
     */
    'name'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaymentOptionDetailsChannel
     */
    'bankShortName'?: string | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof PaymentOptionDetailsChannel
     */
    'currencyCodes'?: Array<string> | null;
    /**
     * 
     * @type {string}
     * @memberof PaymentOptionDetailsChannel
     */
    'iconUrl'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaymentOptionDetailsChannel
     */
    'logoUrl'?: string | null;
    /**
     * 
     * @type {PaymentOptionDetailsPayment}
     * @memberof PaymentOptionDetailsChannel
     */
    'payment'?: PaymentOptionDetailsPayment;
    /**
     * 
     * @type {boolean}
     * @memberof PaymentOptionDetailsChannel
     */
    'isDown'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof PaymentOptionDetailsChannel
     */
    'checkEligibleOption'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof PaymentOptionDetailsChannel
     */
    'ippProviderCode'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaymentOptionDetailsChannel
     */
    'registrationStatus'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaymentOptionDetailsChannel
     */
    'partnerMerchantRefID'?: string | null;
}

