/*
PGW Payment API 4.3

Rest API for PGW payment purpose - LATEST

The version of the OpenAPI document: 4.3


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { PodInfoProviderMerchantDetails } from './pod-info-provider-merchant-details';
import { PodInfoProviderTransactionDetails } from './pod-info-provider-transaction-details';

/**
 * 
 * @export
 * @interface PaymentOptionDetailsInfoProvider
 */
export interface PaymentOptionDetailsInfoProvider {
    /**
     * 
     * @type {string}
     * @memberof PaymentOptionDetailsInfoProvider
     */
    'id'?: string | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof PaymentOptionDetailsInfoProvider
     */
    'channels'?: Array<string> | null;
    /**
     * 
     * @type {PodInfoProviderMerchantDetails}
     * @memberof PaymentOptionDetailsInfoProvider
     */
    'merchantDetails'?: PodInfoProviderMerchantDetails;
    /**
     * 
     * @type {PodInfoProviderTransactionDetails}
     * @memberof PaymentOptionDetailsInfoProvider
     */
    'transactionDetails'?: PodInfoProviderTransactionDetails;
    /**
     * 
     * @type {string}
     * @memberof PaymentOptionDetailsInfoProvider
     */
    'terms'?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof PaymentOptionDetailsInfoProvider
     */
    'termsConsent'?: boolean;
}

