/*
PGW Payment API 4.3

Rest API for PGW payment purpose - LATEST

The version of the OpenAPI document: 4.3


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface PaymentOptionDetailsPaymentCode
 */
export interface PaymentOptionDetailsPaymentCode {
    /**
     * 
     * @type {string}
     * @memberof PaymentOptionDetailsPaymentCode
     */
    'channelCode'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaymentOptionDetailsPaymentCode
     */
    'agentCode'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaymentOptionDetailsPaymentCode
     */
    'agentChannelCode'?: string | null;
}

