/*
PGW Payment API 4.3

Rest API for PGW payment purpose - LATEST

The version of the OpenAPI document: 4.3


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { BrowserDetails } from './browser-details';

/**
 * 
 * @export
 * @interface PaymentExchangeRateConverterRequest
 */
export interface PaymentExchangeRateConverterRequest {
    /**
     * 
     * @type {string}
     * @memberof PaymentExchangeRateConverterRequest
     */
    'bin'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaymentExchangeRateConverterRequest
     */
    'paymentToken': string;
    /**
     * 
     * @type {string}
     * @memberof PaymentExchangeRateConverterRequest
     */
    'locale'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaymentExchangeRateConverterRequest
     */
    'clientID'?: string;
    /**
     * 
     * @type {BrowserDetails}
     * @memberof PaymentExchangeRateConverterRequest
     */
    'browserDetails'?: BrowserDetails;
}

