/*
PGW Payment API 4.3

Rest API for PGW payment purpose - LATEST

The version of the OpenAPI document: 4.3


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface PaymentChannelPreference
 */
export interface PaymentChannelPreference {
    /**
     * 
     * @type {number}
     * @memberof PaymentChannelPreference
     */
    'sequenceNo'?: number;
    /**
     * 
     * @type {string}
     * @memberof PaymentChannelPreference
     */
    'categoryCode'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaymentChannelPreference
     */
    'groupCode'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaymentChannelPreference
     */
    'name'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaymentChannelPreference
     */
    'channelCode'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaymentChannelPreference
     */
    'agentCode'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaymentChannelPreference
     */
    'agentChannelCode'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaymentChannelPreference
     */
    'iconUrl'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaymentChannelPreference
     */
    'logoUrl'?: string | null;
}

