/*
PGW Payment API 4.3

Rest API for PGW payment purpose - LATEST

The version of the OpenAPI document: 4.3


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface PaymentOptionDetailsValidationCard
 */
export interface PaymentOptionDetailsValidationCard {
    /**
     * 
     * @type {Array<string>}
     * @memberof PaymentOptionDetailsValidationCard
     */
    'prefixes'?: Array<string> | null;
    /**
     * 
     * @type {string}
     * @memberof PaymentOptionDetailsValidationCard
     */
    'regex'?: string | null;
}

