/*
PGW Payment API 4.3

Rest API for PGW payment purpose - LATEST

The version of the OpenAPI document: 4.3


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { BrowserDetails } from './browser-details';
import { PaymentParamsRequestV43 } from './payment-params-request-v43';

/**
 * 
 * @export
 * @interface PaymentRequestV43
 */
export interface PaymentRequestV43 {
    /**
     * 
     * @type {PaymentParamsRequestV43}
     * @memberof PaymentRequestV43
     */
    'payment'?: PaymentParamsRequestV43;
    /**
     * 
     * @type {string}
     * @memberof PaymentRequestV43
     */
    'responseReturnUrl'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaymentRequestV43
     */
    'clientIP'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaymentRequestV43
     */
    'paymentToken': string;
    /**
     * 
     * @type {string}
     * @memberof PaymentRequestV43
     */
    'locale'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaymentRequestV43
     */
    'clientID'?: string;
    /**
     * 
     * @type {BrowserDetails}
     * @memberof PaymentRequestV43
     */
    'browserDetails'?: BrowserDetails;
}

