/*
PGW Payment API 4.3

Rest API for PGW payment purpose - LATEST

The version of the OpenAPI document: 4.3


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { PaymentOptionDetailsValidationCard } from './payment-option-details-validation-card';
import { PaymentOptionDetailsValidationCardType } from './payment-option-details-validation-card-type';

/**
 * 
 * @export
 * @interface PaymentOptionDetailsValidation
 */
export interface PaymentOptionDetailsValidation {
    /**
     * 
     * @type {PaymentOptionDetailsValidationCard}
     * @memberof PaymentOptionDetailsValidation
     */
    'cardNo'?: PaymentOptionDetailsValidationCard;
    /**
     * 
     * @type {Array<PaymentOptionDetailsValidationCardType>}
     * @memberof PaymentOptionDetailsValidation
     */
    'cardTypes'?: Array<PaymentOptionDetailsValidationCardType> | null;
}

