/*
PGW Payment API 4.3

Rest API for PGW payment purpose - LATEST

The version of the OpenAPI document: 4.3


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { PaymentLoyaltyReward } from './payment-loyalty-reward';

/**
 * 
 * @export
 * @interface PaymentLoyaltyPointInfoResponse
 */
export interface PaymentLoyaltyPointInfoResponse {
    /**
     * 
     * @type {string}
     * @memberof PaymentLoyaltyPointInfoResponse
     */
    'paymentToken'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaymentLoyaltyPointInfoResponse
     */
    'providerID'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaymentLoyaltyPointInfoResponse
     */
    'providerName'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaymentLoyaltyPointInfoResponse
     */
    'referenceID'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaymentLoyaltyPointInfoResponse
     */
    'providerType'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaymentLoyaltyPointInfoResponse
     */
    'terms'?: string | null;
    /**
     * 
     * @type {Array<PaymentLoyaltyReward>}
     * @memberof PaymentLoyaltyPointInfoResponse
     */
    'rewards'?: Array<PaymentLoyaltyReward> | null;
    /**
     * 
     * @type {string}
     * @memberof PaymentLoyaltyPointInfoResponse
     */
    'respCode'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaymentLoyaltyPointInfoResponse
     */
    'respDesc'?: string | null;
}

