/*
PGW Payment API 4.3

Rest API for PGW payment purpose - LATEST

The version of the OpenAPI document: 4.3


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface PaymentOptionDetailsCustomData
 */
export interface PaymentOptionDetailsCustomData {
    /**
     * 
     * @type {number}
     * @memberof PaymentOptionDetailsCustomData
     */
    'sequenceNo'?: number;
    /**
     * 
     * @type {string}
     * @memberof PaymentOptionDetailsCustomData
     */
    'type'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaymentOptionDetailsCustomData
     */
    'data'?: string | null;
}

