/*
PGW Payment API 4.3

Rest API for PGW payment purpose - LATEST

The version of the OpenAPI document: 4.3


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { CurrencyAPMMCCFxRate } from './currency-apmmccfx-rate';

/**
 * 
 * @export
 * @interface PaymentApmMccExchangeRateResponse
 */
export interface PaymentApmMccExchangeRateResponse {
    /**
     * 
     * @type {Array<CurrencyAPMMCCFxRate>}
     * @memberof PaymentApmMccExchangeRateResponse
     */
    'fxRates'?: Array<CurrencyAPMMCCFxRate> | null;
    /**
     * 
     * @type {string}
     * @memberof PaymentApmMccExchangeRateResponse
     */
    'paymentToken'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaymentApmMccExchangeRateResponse
     */
    'respCode'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaymentApmMccExchangeRateResponse
     */
    'respDesc'?: string | null;
}

