/*
PGW Payment API 4.3

Rest API for PGW payment purpose - LATEST

The version of the OpenAPI document: 4.3


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { IppPlan } from './ipp-plan';
import { PaymentOptionDetailsCustomData } from './payment-option-details-custom-data';
import { PaymentOptionDetailsInfoProvider } from './payment-option-details-info-provider';

/**
 * 
 * @export
 * @interface PaymentOptionDetailsInfo
 */
export interface PaymentOptionDetailsInfo {
    /**
     * 
     * @type {string}
     * @memberof PaymentOptionDetailsInfo
     */
    'terms'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaymentOptionDetailsInfo
     */
    'promoUrl'?: string | null;
    /**
     * 
     * @type {Array<IppPlan>}
     * @memberof PaymentOptionDetailsInfo
     */
    'plans'?: Array<IppPlan> | null;
    /**
     * 
     * @type {Array<PaymentOptionDetailsCustomData>}
     * @memberof PaymentOptionDetailsInfo
     */
    'customData'?: Array<PaymentOptionDetailsCustomData> | null;
    /**
     * 
     * @type {PaymentOptionDetailsInfoProvider}
     * @memberof PaymentOptionDetailsInfo
     */
    'provider'?: PaymentOptionDetailsInfoProvider;
    /**
     * 
     * @type {string}
     * @memberof PaymentOptionDetailsInfo
     */
    'learnMoreUrl'?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof PaymentOptionDetailsInfo
     */
    'termsConsent'?: boolean;
}

