/*
PGW Payment API 4.3

Rest API for PGW payment purpose - LATEST

The version of the OpenAPI document: 4.3


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { PaymentOptionDetailsPaymentCode } from './payment-option-details-payment-code';
import { PaymentParamsDataRequestV43 } from './payment-params-data-request-v43';

/**
 * 
 * @export
 * @interface PaymentParamsRequestV43
 */
export interface PaymentParamsRequestV43 {
    /**
     * 
     * @type {PaymentParamsDataRequestV43}
     * @memberof PaymentParamsRequestV43
     */
    'data'?: PaymentParamsDataRequestV43;
    /**
     * 
     * @type {PaymentOptionDetailsPaymentCode}
     * @memberof PaymentParamsRequestV43
     */
    'code'?: PaymentOptionDetailsPaymentCode;
}

