/*
PGW Payment API 4.3

Rest API for PGW payment purpose - LATEST

The version of the OpenAPI document: 4.3


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { CreditCardTokenV43 } from './credit-card-token-v43';

/**
 * 
 * @export
 * @interface PaymentCardTokenResponseV43
 */
export interface PaymentCardTokenResponseV43 {
    /**
     * 
     * @type {string}
     * @memberof PaymentCardTokenResponseV43
     */
    'paymentToken'?: string | null;
    /**
     * 
     * @type {Array<CreditCardTokenV43>}
     * @memberof PaymentCardTokenResponseV43
     */
    'customerToken'?: Array<CreditCardTokenV43> | null;
    /**
     * 
     * @type {string}
     * @memberof PaymentCardTokenResponseV43
     */
    'respCode'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaymentCardTokenResponseV43
     */
    'respDesc'?: string | null;
}

