/*
PGW Payment API 4.3

Rest API for PGW payment purpose - LATEST

The version of the OpenAPI document: 4.3


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { PaymentChannelPreference } from './payment-channel-preference';
import { UserPreference } from './user-preference';

/**
 * 
 * @export
 * @interface PaymentUserPreference
 */
export interface PaymentUserPreference {
    /**
     * 
     * @type {UserPreference}
     * @memberof PaymentUserPreference
     */
    'preference'?: UserPreference;
    /**
     * 
     * @type {Array<PaymentChannelPreference>}
     * @memberof PaymentUserPreference
     */
    'paymentChannels'?: Array<PaymentChannelPreference> | null;
}

