/*
PGW Payment API 4.3

Rest API for PGW payment purpose - LATEST

The version of the OpenAPI document: 4.3


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { MerchantConfiguration } from './merchant-configuration';
import { PaymentOptionDetailsChannel } from './payment-option-details-channel';
import { PaymentOptionDetailsValidation } from './payment-option-details-validation';

/**
 * 
 * @export
 * @interface PaymentOptionDetailsResponse
 */
export interface PaymentOptionDetailsResponse {
    /**
     * 
     * @type {number}
     * @memberof PaymentOptionDetailsResponse
     */
    'totalChannel'?: number;
    /**
     * 
     * @type {string}
     * @memberof PaymentOptionDetailsResponse
     */
    'name'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaymentOptionDetailsResponse
     */
    'categoryCode'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaymentOptionDetailsResponse
     */
    'groupCode'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaymentOptionDetailsResponse
     */
    'iconUrl'?: string | null;
    /**
     * 
     * @type {Array<PaymentOptionDetailsChannel>}
     * @memberof PaymentOptionDetailsResponse
     */
    'channels'?: Array<PaymentOptionDetailsChannel> | null;
    /**
     * 
     * @type {PaymentOptionDetailsValidation}
     * @memberof PaymentOptionDetailsResponse
     */
    'validation'?: PaymentOptionDetailsValidation;
    /**
     * 
     * @type {MerchantConfiguration}
     * @memberof PaymentOptionDetailsResponse
     */
    'configuration'?: MerchantConfiguration;
    /**
     * 
     * @type {string}
     * @memberof PaymentOptionDetailsResponse
     */
    'respCode'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaymentOptionDetailsResponse
     */
    'respDesc'?: string | null;
}

