/*
PGW Payment API 4.3

Rest API for PGW payment purpose - LATEST

The version of the OpenAPI document: 4.3


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { CurrencyFxRate } from './currency-fx-rate';

/**
 * 
 * @export
 * @interface PaymentExchangeRateConverterResponse
 */
export interface PaymentExchangeRateConverterResponse {
    /**
     * 
     * @type {Array<CurrencyFxRate>}
     * @memberof PaymentExchangeRateConverterResponse
     */
    'fxRates'?: Array<CurrencyFxRate> | null;
    /**
     * 
     * @type {string}
     * @memberof PaymentExchangeRateConverterResponse
     */
    'providerCode'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof PaymentExchangeRateConverterResponse
     */
    'expire'?: number | null;
    /**
     * 
     * @type {string}
     * @memberof PaymentExchangeRateConverterResponse
     */
    'paymentToken'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaymentExchangeRateConverterResponse
     */
    'respCode'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaymentExchangeRateConverterResponse
     */
    'respDesc'?: string | null;
}

