/*
PGW Payment API 4.3

Rest API for PGW payment purpose - LATEST

The version of the OpenAPI document: 4.3


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface PaymentLoyaltyReward
 */
export interface PaymentLoyaltyReward {
    /**
     * 
     * @type {number}
     * @memberof PaymentLoyaltyReward
     */
    'sequenceNo'?: number;
    /**
     * 
     * @type {string}
     * @memberof PaymentLoyaltyReward
     */
    'id'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaymentLoyaltyReward
     */
    'currencyCode'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof PaymentLoyaltyReward
     */
    'totalPoints'?: number;
    /**
     * 
     * @type {string}
     * @memberof PaymentLoyaltyReward
     */
    'label'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof PaymentLoyaltyReward
     */
    'point'?: number;
    /**
     * 
     * @type {boolean}
     * @memberof PaymentLoyaltyReward
     */
    'forceToSelectReward'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof PaymentLoyaltyReward
     */
    'name'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaymentLoyaltyReward
     */
    'type'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof PaymentLoyaltyReward
     */
    'amount'?: number;
    /**
     * 
     * @type {number}
     * @memberof PaymentLoyaltyReward
     */
    'quantity'?: number;
    /**
     * 
     * @type {number}
     * @memberof PaymentLoyaltyReward
     */
    'price'?: number;
}

