/*
PGW Payment API 4.3

Rest API for PGW payment purpose - LATEST

The version of the OpenAPI document: 4.3


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface PodInfoProviderMerchantDetails
 */
export interface PodInfoProviderMerchantDetails {
    /**
     * 
     * @type {string}
     * @memberof PodInfoProviderMerchantDetails
     */
    'id'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PodInfoProviderMerchantDetails
     */
    'name'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PodInfoProviderMerchantDetails
     */
    'countryCode'?: string | null;
}

