/*
PGW Payment API 4.3

Rest API for PGW payment purpose - LATEST

The version of the OpenAPI document: 4.3


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface Recurring
 */
export interface Recurring {
    /**
     * 
     * @type {string}
     * @memberof Recurring
     */
    'amount'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof Recurring
     */
    'interval'?: number;
    /**
     * 
     * @type {number}
     * @memberof Recurring
     */
    'count'?: number;
    /**
     * 
     * @type {string}
     * @memberof Recurring
     */
    'chargeNextDate'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Recurring
     */
    'chargeOnDate'?: string | null;
}

