/*
PGW Payment API 4.3

Rest API for PGW payment purpose - LATEST

The version of the OpenAPI document: 4.3


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface RedirectFrontEndPostPaymentRedirectRequest
 */
export interface RedirectFrontEndPostPaymentRedirectRequest {
    /**
     * 
     * @type {string}
     * @memberof RedirectFrontEndPostPaymentRedirectRequest
     */
    'payResponse'?: string;
    /**
     * 
     * @type {string}
     * @memberof RedirectFrontEndPostPaymentRedirectRequest
     */
    'isLeaveApp'?: string;
}

