/*
PGW Payment API 4.3

Rest API for PGW payment purpose - LATEST

The version of the OpenAPI document: 4.3


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface ResponsePaymentChannel
 */
export interface ResponsePaymentChannel {
    /**
     * 
     * @type {number}
     * @memberof ResponsePaymentChannel
     */
    'id'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof ResponsePaymentChannel
     */
    'sequenceNo'?: number;
    /**
     * 
     * @type {string}
     * @memberof ResponsePaymentChannel
     */
    'name'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ResponsePaymentChannel
     */
    'code'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ResponsePaymentChannel
     */
    'iconUrl'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ResponsePaymentChannel
     */
    'logoUrl'?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof ResponsePaymentChannel
     */
    'default'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ResponsePaymentChannel
     */
    'channelCode'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ResponsePaymentChannel
     */
    'agentChannelCode'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ResponsePaymentChannel
     */
    'optionName'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ResponsePaymentChannel
     */
    'paymentCode'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ResponsePaymentChannel
     */
    'qrType'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ResponsePaymentChannel
     */
    'expirationTimer'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ResponsePaymentChannel
     */
    'expirationDescription'?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof ResponsePaymentChannel
     */
    'expiration'?: boolean;
}

