/*
PGW Payment API 4.3

Rest API for PGW payment purpose - LATEST

The version of the OpenAPI document: 4.3


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface TransactionStatusPayment
 */
export interface TransactionStatusPayment {
    /**
     * 
     * @type {string}
     * @memberof TransactionStatusPayment
     */
    'description'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TransactionStatusPayment
     */
    'code'?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof TransactionStatusPayment
     */
    'autoRedirect'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof TransactionStatusPayment
     */
    'redirectImmediately'?: boolean;
    /**
     * 
     * @type {number}
     * @memberof TransactionStatusPayment
     */
    'autoRedirectionTimer'?: number;
    /**
     * 
     * @type {string}
     * @memberof TransactionStatusPayment
     */
    'frontendReturnUrl'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TransactionStatusPayment
     */
    'frontendReturnData'?: string | null;
}

