/*
PGW Payment API 4.3

Rest API for PGW payment purpose - LATEST

The version of the OpenAPI document: 4.3


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { TransactionStatusAdditionalInfo } from './transaction-status-additional-info';

/**
 * 
 * @export
 * @interface TransactionStatusResponse
 */
export interface TransactionStatusResponse {
    /**
     * 
     * @type {string}
     * @memberof TransactionStatusResponse
     */
    'locale'?: string | null;
    /**
     * 
     * @type {TransactionStatusAdditionalInfo}
     * @memberof TransactionStatusResponse
     */
    'additionalInfo'?: TransactionStatusAdditionalInfo;
    /**
     * 
     * @type {string}
     * @memberof TransactionStatusResponse
     */
    'invoiceNo'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TransactionStatusResponse
     */
    'channelCode'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TransactionStatusResponse
     */
    'respCode'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TransactionStatusResponse
     */
    'respDesc'?: string | null;
}

