/*
PGW Payment API 4.3

Rest API for PGW payment purpose - LATEST

The version of the OpenAPI document: 4.3


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface TransactionStatusRewards
 */
export interface TransactionStatusRewards {
    /**
     * 
     * @type {number}
     * @memberof TransactionStatusRewards
     */
    'totalPrice'?: number;
    /**
     * 
     * @type {number}
     * @memberof TransactionStatusRewards
     */
    'totalAmount'?: number;
    /**
     * 
     * @type {string}
     * @memberof TransactionStatusRewards
     */
    'name'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TransactionStatusRewards
     */
    'type'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof TransactionStatusRewards
     */
    'amount'?: number;
    /**
     * 
     * @type {number}
     * @memberof TransactionStatusRewards
     */
    'quantity'?: number;
    /**
     * 
     * @type {number}
     * @memberof TransactionStatusRewards
     */
    'price'?: number;
}

