/*
PGW Payment API 4.3

Rest API for PGW payment purpose - LATEST

The version of the OpenAPI document: 4.3


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { TransactionStatusLoyaltyInfo } from './transaction-status-loyalty-info';

/**
 * 
 * @export
 * @interface TransactionStatusInfo
 */
export interface TransactionStatusInfo {
    /**
     * 
     * @type {string}
     * @memberof TransactionStatusInfo
     */
    'description'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TransactionStatusInfo
     */
    'dateTime'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TransactionStatusInfo
     */
    'agentCode'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TransactionStatusInfo
     */
    'channelCode'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TransactionStatusInfo
     */
    'data'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TransactionStatusInfo
     */
    'amount'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TransactionStatusInfo
     */
    'currencyCode'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TransactionStatusInfo
     */
    'invoiceNo'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof TransactionStatusInfo
     */
    'installmentPeriod'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof TransactionStatusInfo
     */
    'payLaterPeriod'?: number | null;
    /**
     * 
     * @type {string}
     * @memberof TransactionStatusInfo
     */
    'interestType'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof TransactionStatusInfo
     */
    'interestRate'?: number | null;
    /**
     * 
     * @type {string}
     * @memberof TransactionStatusInfo
     */
    'monthlyPayment'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TransactionStatusInfo
     */
    'ippAdditionalInfo'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TransactionStatusInfo
     */
    'remainderChargeMode'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof TransactionStatusInfo
     */
    'remainderChargeAmount'?: number | null;
    /**
     * 
     * @type {Array<TransactionStatusLoyaltyInfo>}
     * @memberof TransactionStatusInfo
     */
    'loyaltyPoints'?: Array<TransactionStatusLoyaltyInfo> | null;
}

