/*
PGW Payment API 4.3

Rest API for PGW payment purpose - LATEST

The version of the OpenAPI document: 4.3


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface UserPreference
 */
export interface UserPreference {
    /**
     * 
     * @type {string}
     * @memberof UserPreference
     */
    'name'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserPreference
     */
    'email'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserPreference
     */
    'mobileNo'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserPreference
     */
    'mobileNoPrefix'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserPreference
     */
    'locale'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserPreference
     */
    'currencyCode'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserPreference
     */
    'countryCode'?: string | null;
}

